Feature/index html
so-suke/mosha_recruit_ver2 pull request #1
Opened 2019-04-23 11:17 UTC by so-suke

2019-04-25 15:40 UTC, s-higu requested changes

2019-04-25 15:40 UTC, higusyun commented on index.html
> +      <nav id="headerNav" class="header__nav">
`ID` はどういった目的で使用予定でしょう？

2019-04-25 15:40 UTC, higusyun commented on index.html
> +            <a href="service/">私たちについて<span class="icon"></span></a>
前回指摘しそびれかもですが、こういった「共通の」アイコン類の有無はクラス管理にしてCSSの擬似要素で切り替えたほうが楽ですね！

2019-04-25 15:40 UTC, higusyun commented on index.html
> +          <li class="header__navItem">
応募ボタンは同じ属性じゃないかとー

2019-04-25 15:40 UTC, higusyun commented on index.html
> +        <div class="back back--1">
こういう連番の使い方はOKです！
ただいずれも絶対配置かと思うので `共通クラス名 共通クラス名--数字` に統一でいいかと思います。
アニメーションの都合上カテゴリわけが必要かと思いますが、そういった時は無理にクラス名を付与するよりカスタムデータにしたほうがパッと見の可読性も高いです。

2019-04-25 15:40 UTC, higusyun commented on index.html
> +          <br>
`br` は文中内の「改行」に使うものです。余白目的で使うのはNGです

2019-04-25 15:40 UTC, higusyun commented on index.html
> +          <span class="title title--1">
連番はいいとして、特に個別にクラスをつける必要をあまり感じないのですがどういった実装で考えてますかね？

2019-04-25 15:40 UTC, higusyun commented on index.html
> +          <img class="logoImg" src="img/logo.svg" alt="リクルートライフスタイル">
順番的に `ul` と逆な気がします

2019-04-25 18:32 UTC, so-suke commented on index.html
> +          <span class="title title--1">
こちらの部分に関しましては、
`title--1`に`padding:left:16px`
`title--2`で`padding:right:16px`
を設定しようと考えております。
このような説明で、問題ないでしょうか。

2019-04-25 18:44 UTC, so-suke commented on index.html
> +          <img class="logoImg" src="img/logo.svg" alt="リクルートライフスタイル">
ご指摘いただけました通り
PCサイズの場合ですと、HTML構造と見た目が逆になっております。
しかしながら、スマホサイズになりますと、見た目が逆転し
HTML構造と見た目が正しくなります。

元サイトですと、このようなHTML構造となっておりました。
おそらく、スマホサイズをメインに考えて作成されたのだと思いますが。
PCサイズをメインにしたHTML構造の方がいいでしょうか。

2019-04-25 18:48 UTC, so-suke commented on index.html
> +            <a href="service/">私たちについて<span class="icon"></span></a>
こちらは、`<span class="icon"></span>`を削除して`<a href="service/">`にクラスを付与し
  疑似要素を設定するという認識で合っていますでしょうか。
  実は、iconクラスには、(::before, ::after)の両方を指定してプラス記号を表現します。
  また、アニメーションでプラス記号の棒を動かして、マイナス記号にするようにします。
  こちらの動きを実現するためには、現在の方法のままの方が良いかと思いますがいかがでしょうか。

2019-04-25 18:55 UTC, so-suke commented on index.html
> +      <nav id="headerNav" class="header__nav">
ご指摘ありがとうございます。修正しました。

2019-04-25 18:55 UTC, so-suke commented on index.html
> +          <li class="header__navItem">
ご指摘ありがとうございます。修正しました。

2019-04-25 18:55 UTC, so-suke commented on index.html
> +        <div class="back back--1">
ご指摘ありがとうございます。修正しました。

2019-04-25 18:56 UTC, so-suke commented on index.html
> +          <br>
コメントありがとうございます。修正しました。

2019-04-26 08:18 UTC, higusyun commented on index.html
> +            <a href="service/">私たちについて<span class="icon"></span></a>
あーなるほど。。
SVGで作っちゃうことが多いので擬似要素は想定してませんでした。
擬似要素であれば他に方法ないのでインラインで大丈夫です。

2019-04-26 08:20 UTC, higusyun commented on index.html
> +          <img class="logoImg" src="img/logo.svg" alt="リクルートライフスタイル">
何をファーストとするかの概念によりますね。
モバイルファーストであればモバイルベースのコードになりますし、その逆も然りです。
ただこのデザインはモバイルファーストデザインではないので、PCベースで作っていくことを考えるとPCを基準にすべきかと思います。

2019-04-26 08:23 UTC, higusyun commented on index.html
> +          <span class="title title--1">
あーSVGに余白がないんですね。。
完パコなデザインにしたい時は素材もそういった状態にしておくのがベストなのでデザイナーさん側の配慮ミスで実装側で対処してる感じですかね。
それであれば問題ないです。

2019-04-26 11:06 UTC, merged