Feature/task style
so-suke/mosha_recruit_ver2 pull request #2
Opened 2019-04-26 17:54 UTC by so-suke

2019-04-28 15:05 UTC, s-higu requested changes

2019-04-28 15:05 UTC, s-higu commented on scss/components/_header.scss
> +    padding: 24px 40px;
一番大きい画面サイズのスタイルを定義しておいて、画面幅が小さくなるにつれてメディアクエリで処理を振り分けるのがレスポンシブスタイルの書き方です（モバイルファーストであればその逆）。
`min-width` であるこのスタイルがデフォルトスタイルではなくメディアクエリ内にあるのはBADです。

2019-04-28 15:05 UTC, s-higu commented on scss/components/_header.scss
> +      top: -10px;
インライン要素の垂直位置調整には `vertical-align` を使います

2019-04-28 15:05 UTC, s-higu commented on scss/components/_header.scss
> +  align-items: center;
このへんのよく使うやつは `mixin` にしておきたいです

2019-04-28 15:05 UTC, s-higu commented on scss/components/_list.scss
> +      @include breakMinWidth($breakpointSP) {
上と重複してそうです

2019-04-28 15:05 UTC, s-higu commented on scss/components/_list.scss
> +          padding: 0 4px;
`a` に隣接する要素がないので `li` の余白ですね

2019-04-28 15:05 UTC, s-higu commented on scss/components/_list.scss
> +          &:hover {
`scale` の動きは未実装ですかね

2019-04-28 15:05 UTC, s-higu commented on scss/components/_btn.scss
> +    & .bar {
このあたり珍しい組み方しましたね・・
3本線のための `span` が3つあった方が実装状態も確認しやすくやりやすいと思うんですが、何か参考にしたりしましたか？

2019-04-28 15:05 UTC, s-higu commented on scss/components/_layout.scss
> +.entireBackgroud {
あんまり `lauout` にゴリゴリと書くのはよくない（見た感じレイアウト以外のスタイル定義も多いので・・）ので、膨大になってしまう場合には、 `entireBackgroud` はentireBackgroudに、 `visual` はvisualにみたいに定義したほうがいいです

2019-04-28 15:05 UTC, s-higu commented on index.html
> +        <span class="title title--1">
インラインなために画面を広くした時に1行になってしまうので2行を維持しましょう

2019-04-28 15:05 UTC, s-higu commented on scss/components/_layout.scss
> +          top: calc(49% - 191px);
通常であれば `top: 可変の値（%やvwなど）` と実装しそうですが、このあたりの値はどうやって求めましたか？
一部のプロトタイプツールで算出できるものがありますが、それに基づいてないとすると少なくとも引かれる値は固定値にしておかないとかなり人の手が入れにくい実装方法です。

2019-04-28 15:05 UTC, s-higu commented on scss/components/_title.scss
> +          margin-bottom: 20px;
この `margin-bottom` はなんでしょう？

2019-04-28 15:05 UTC, s-higu commented on scss/components/_title.scss
> +      margin-bottom: calc(-24vw / 4.8);
この2行はどうやって求めましたか？
根拠やルールがわかりにくい計算は実装者の手が入れにくくなるので避けてください

2019-04-28 15:05 UTC, s-higu commented on scss/components/_title.scss
> +      margin-bottom: calc(24vw / 4.8);
画像のほうをレスポンシブ化すればいいと思うんですがどうでしょう。
このへんの計算も根拠がわかりづらいです

2019-04-28 15:05 UTC, s-higu commented on scss/components/_list.scss
> +        max-width: 33.333333%;
小数点計算にはブラウザに反映できる限界があるのと、これではあまりが発生するので `calc` で演算するようにしましょう

2019-04-28 15:05 UTC, s-higu commented on index.html
> +                  <source media="(min-width:768px)" srcset="img/ttl_top_culture.svg">
たしかに `srcset` 便利なんですが、今回のサイトのように数が多い場合はメディアクエリが直書きになる点を考慮するとかなりメンテナンス性が悪い実装方法です。
修正前のコードのようにカスタムデータ属性にパスを持たせておいて、一括切り替えしたほうがよく、そのためのカスタムデータ属性かと思っていたんですがちがったでしょうか？

2019-04-28 15:05 UTC, higusyun commented on scss/style.scss
> +@import "./components/animation_active";
標準時に何らかのトリガーがあってクラスを付与するイメージかと思うので、基本はクラスの上書きあるいは付け替えになると思います。
この2つに分けたことにはどんな理由や考えていることがありますか？

2019-04-30 00:19 UTC, so-suke commented on scss/components/_list.scss
> +      @include breakMinWidth($breakpointSP) {
コメントありがとうございます。修正しました。

2019-05-01 18:33 UTC, so-suke commented on scss/components/_list.scss
> +          &:hover {
こちらの動きは、アニメーション実装段階でやろうと思います。

2019-05-02 10:56 UTC, so-suke commented on scss/components/_header.scss
> +    padding: 24px 40px;
コメントありがとうございます。修正しました。

2019-05-02 10:56 UTC, so-suke commented on scss/components/_header.scss
> +      top: -10px;
コメントありがとうございます。修正しました。

2019-05-02 10:57 UTC, so-suke commented on scss/components/_header.scss
> +  align-items: center;
コメントありがとうございます。flex関連のmixinを定義するようにしました。

2019-05-02 10:58 UTC, so-suke commented on scss/components/_list.scss
> +          &:hover {
コメントありがとうございます。scaleの動きつけました。

2019-05-02 10:59 UTC, so-suke commented on scss/components/_btn.scss
> +    & .bar {
コメントありがとうございます。span3つで作るように修正しました。

2019-05-02 10:59 UTC, so-suke commented on scss/components/_layout.scss
> +.entireBackgroud {
コメントありがとうございます。大きめのものを、個々のファイルに分割しました。

2019-05-02 11:00 UTC, so-suke commented on index.html
> +        <span class="title title--1">
コメントありがとうございます。
ブロック化し、1行にならないよう修正しました。

2019-05-02 11:00 UTC, so-suke commented on scss/components/_layout.scss
> +          top: calc(49% - 191px);
コメントありがとうございます。top(%)の形に修正しました。

2019-05-02 11:01 UTC, so-suke commented on scss/components/_title.scss
> +          margin-bottom: 20px;
コメントありがとうございます。不要でしたので削除しました。

2019-05-02 11:02 UTC, so-suke commented on scss/components/_title.scss
> +      margin-bottom: calc(-24vw / 4.8);
コメントありがとうございます。function.scssにて計算用の関数を定義しました。

2019-05-02 11:03 UTC, so-suke commented on scss/components/_title.scss
> +      margin-bottom: calc(24vw / 4.8);
コメントありがとうございます。画像にレスポンシブ幅が適用されるように修正しました。

2019-05-02 11:03 UTC, so-suke commented on scss/components/_list.scss
> +        max-width: 33.333333%;
コメントありがとうございます。calc使用するように修正しました。

2019-05-02 11:04 UTC, so-suke commented on index.html
> +                  <source media="(min-width:768px)" srcset="img/ttl_top_culture.svg">
コメントありがとうございます。srcset削除するように修正しました。

2019-05-03 17:43 UTC, s-higu requested changes

2019-05-03 17:43 UTC, higusyun commented on scss/mixins/_mixins.scss
> +@mixin flexCenterCenter() {
機能をわかりやすくしたほうがいいですね。
`CenterCenter` だと何が何なんだ…となってしまうので、ここに関しては `centering` とかでいいかと。

2019-05-03 17:43 UTC, higusyun commented on scss/mixins/_mixins.scss
> +  justify-content: space-between;
以降もそうですが
```
display: flex;
align-items: center;
```
このあたりは共通なので、 `justify-content` の値を引数にして使いまわせる `mixin` にすればいいかと思います。
`centering` 用と `flex` 用の2種類とすればだいぶシンプルになるかと。

2019-05-03 17:45 UTC, s-higu requested changes

2019-05-03 17:45 UTC, higusyun commented on scss/_functions.scss
> +@function calcSP_Val($originalPixelNum) {
記法がまざりすぎなのでキャメルケースに統一しましょう（他も全体的に）

2019-05-03 17:51 UTC, s-higu requested changes

2019-05-03 17:51 UTC, higusyun commented on scss/components/_list.scss
> +            transition: opacity 0.3s, transform 0.3s cubic-bezier(0.215, 0.61, 0.355, 1);
今回はそこまで同じ表現は重複しないサイトですが、 `scale` や `transition` のスピードなどはなるべく変数化しておいたほうがいいです。
通常は同じ値を使い回すことが多いので！

2019-05-03 17:51 UTC, higusyun commented on scss/components/_list.scss
> +              opacity: 0.6;
元サイトの実装見てないのでわからないですが、 `opacity` も複数の値がやたらに出てこないのであれば変数化しておきたいです

2019-05-03 17:55 UTC, s-higu requested changes

2019-05-03 17:55 UTC, higusyun commented on scss/style.scss
> +@import "./functions";
言ってしまえばどれも `function` なのでこれだとだいぶ抽象的です。
機能名にしましょう。

2019-05-03 17:55 UTC, higusyun commented on scss/style.scss
> +@import "./components/visual";
`/components` ディレクトリによってコンポーネントであることは一目瞭然なのでコメントはなしにまとめちゃったほうがわかりやすいです
```
// components
@import "./components/header";
@import "./components/visual";
以下略
```

2019-05-04 07:16 UTC, so-suke commented on scss/mixins/_mixins.scss
> +@mixin flexCenterCenter() {
コメントありがとうございます。修正しました。

2019-05-04 07:16 UTC, so-suke commented on scss/mixins/_mixins.scss
> +  justify-content: space-between;
コメントありがとうございます。修正しました。

2019-05-04 08:22 UTC, so-suke commented on scss/_functions.scss
> +@function calcSP_Val($originalPixelNum) {
コメントありがとうございます。修正しました。

2019-05-04 08:22 UTC, so-suke commented on scss/components/_list.scss
> +            transition: opacity 0.3s, transform 0.3s cubic-bezier(0.215, 0.61, 0.355, 1);
コメントありがとうございます。修正しました。

2019-05-04 08:38 UTC, so-suke commented on scss/components/_list.scss
> +              opacity: 0.6;
コメントありがとうございます。

2019-05-04 10:04 UTC, so-suke commented on scss/style.scss
> +@import "./functions";
コメントありがとうございます。修正しました。

2019-05-04 10:04 UTC, so-suke commented on scss/style.scss
> +@import "./components/visual";
コメントありがとうございます。修正しました。

2019-05-05 18:29 UTC, s-higu requested changes

2019-05-05 18:29 UTC, higusyun commented on scss/mixins/_mixins.scss
> +@mixin flex($params: null) {
こんなに複雑化します…？
```
display: flex;
align-items: center;
```
が共通で、
```
justify-content: ○○
```
が差異なので、○○の部分を引数にしておけばいいだけかと

2019-05-05 18:34 UTC, s-higu requested changes

2019-05-05 18:34 UTC, higusyun commented on scss/variables/_variables.scss
> +$speedFast: 0.3s;
`speed` 自体に何の速度であるかを表す意味はないので、名詞として使うケースはあまりないです。
よく使うのは `fadeSpeed` や `swingSpeed` などイディオム的なものが多いです。
今回であれば `transition` に関する `speed` なので、 `transitionFast` or `transitionSpeedFast` などがいいと思います

2019-05-05 18:38 UTC, s-higu requested changes

2019-05-05 18:38 UTC, higusyun commented on scss/variables/_variables.scss
> +$opacityDeep: .8;
`light` の対義語は `deep` ではないのでちょいと微妙ですね・・
濃淡を表したいので「薄い」「標準」「濃い」くらいのレベルで構成できるといいです

2019-05-08 04:48 UTC, merged